version: '3.8'

services:
  # Service PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: healthDonate
      POSTGRES_PASSWORD: healthPW
      POSTGRES_DB: healthdonateBD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Service smtp4dev
  smtp:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    ports:
      - "3000:80"  # Interface web
      - "2525:25"  # Port SMTP
    volumes:
      - smtp4dev_data:/smtp4dev
    restart: unless-stopped
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  smtp4dev_data: